name: Test commands

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

jobs:
  test:
    # Build on Monterey and later Ventura (Not public released yet: https://github.com/actions/runner-images)
    strategy:
      matrix:
        os: [macos-12]
#        php: ['8.3', '8.2', '8.1', '8.0', '7.4', '7.3', '7.2', '7.1']
        php: ['8.1']
    runs-on: ${{matrix.os}}
    name: ${{matrix.os}} with ${{matrix.php}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: '[INSTALL] Install PHP 8.0'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL, max_execution_time=-1, memory_limit=512M
          tools: composer:v2
          coverage: none
      - name: '[INSTALL] Brew'
        run: brew cleanup
      - name: '[INSTALL] Composer install'
        run: composer install --no-interaction --prefer-dist
      - name: '[INSTALL] Valet install'
        run: ./valet-plus install

      - name: '[TEST] Nginx'
        run: |
          sudo nginx -t
          curl 127.0.0.1 | grep "Valet - Not Found"

      - name: '[TEST] DB commands'
        run: |
          ./valet-plus db create testci | grep "\"testci\" created successfully"
          ./valet-plus db list | grep "testci"
          ./valet-plus db drop testci -y | grep "\"testci\" dropped successfully"

      - name: '[TEST] PHP switch'
        run: |
          ./valet-plus use ${{matrix.php}}
          php -v | grep ${{matrix.php}}
      - name: '[TEST] xdebug on and off'
        run: |
          ./valet-plus xdebug on
          ./valet-plus xdebug off
      - name: '[TEST] memcache on and off'
        run: |
          ./valet-plus memcache on
          ./valet-plus memcache off
